/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['Space Mono', 'monospace'],
      },
      colors: {
        // Ethereal Precision Design System
        ethereal: {
          background: '#101415',
          surface: '#1c2021',
          'surface-low': '#181c1d',
          'surface-high': '#272b2c',
          'surface-highest': '#313536',
          primary: '#d0bcff',
          'on-primary': '#3c0091',
          'primary-container': '#a078ff',
          'primary-fixed': '#e9ddff',
          'primary-fixed-dim': '#d0bcff',
          secondary: '#ccbeff',
          'on-secondary': '#332664',
          'secondary-container': '#4a3d7c',
          'secondary-fixed': '#e7deff',
          'secondary-fixed-dim': '#ccbeff',
          tertiary: '#4cd7f6',
          'on-tertiary': '#003640',
          'tertiary-container': '#009eb9',
          'tertiary-fixed': '#acedff',
          'tertiary-fixed-dim': '#4cd7f6',
          outline: '#958ea0',
          'outline-variant': '#494454',
          'on-surface': '#e0e3e4',
          'on-surface-variant': '#cbc3d7',
          'on-background': '#e0e3e4',
          error: '#ffb4ab',
          'on-error': '#690005',
          'error-container': '#93000a',
        },
        // Electric Violet accent
        electric: {
          violet: '#8b5cf6',
          violet-hover: '#7c3aed',
        },
        // Legacy fallbacks
        gray: {
          50: '#f8fafc',
          100: '#e0e3e4',
          200: '#cbc3d7',
          300: '#958ea0',
          400: '#494454',
          500: '#313536',
          600: '#272b2c',
          700: '#1c2021',
          800: '#181c1d',
          900: '#101415',
          950: '#0b0f10',
        },
      },
      spacing: {
        'section-desktop': '160px',
        'section-mobile': '80px',
        'gutter': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-xl': '64px',
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      backdropBlur: {
        'glass': '12px',
        'glass-lg': '20px',
      },
      boxShadow: {
        'ghost': '0 0 0 1px rgba(255, 255, 255, 0.15)',
        'ghost-hover': '0 0 0 1px rgba(255, 255, 255, 0.4), 0 0 64px -5px rgba(139, 92, 246, 0.1)',
        'glass': '0 4px 32px rgba(0, 0, 0, 0.4)',
      },
      fontSize: {
        'display-lg': ['84px', { lineHeight: '92px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-lg-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}